apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: next-js-app-pipeline-run-
spec:
  pipelineRef:
    name: next-js-app-pipeline
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi