apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: next-js-app-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: next-js-app-pipeline
  params:
    - name: app-name
      value: next-js-app
    - name: image-repo
      value: quay.io/fabianschwab/next-js-app
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi